import { Boardgame } from './models/boardgame';

export const gamesList: Boardgame[] = [
    { name: 'Patchwork', players: { min: 2, max: 2 } },
    { name: 'Колонизаторы', players: { min: 3, max: 4 } },
    { name: 'Alias', players: { min: 4, max: null } },
    { name: 'Подорож Україною', players: { min: 3, max: 5 } },
    { name: 'Codenames', players: { min: 4, max: null } },
    { name: 'Звёздные Империи', players: { min: 2, max: 2 } },
    { name: 'Race for the Galaxy', players: { min: 2, max: 4 } },
    { name: 'Rummikub', players: { min: 2, max: 4 } },
    { name: 'Scrabble (eng)', players: { min: 2, max: 4 } },
    { name: 'Цитадели (делюкс)', players: { min: 3, max: 8 } },
    { name: 'Fluxx', players: { min: 3, max: 6 } },
    { name: '7 Чудес: Дуэль', players: { min: 2, max: 2 } },
    { name: 'Гильдии Лаара', players: { min: 4, max: 4 } },
    { name: 'Uno', players: { min: 3, max: null } },
    { name: 'Золото Инков', players: { min: 4, max: null } },
    { name: 'Wrong Chemistry (Молекула)', players: { min: 2, max: 3 } },
    { name: 'Fairy Tale', players: { min: 4, max: 5 } },
    { name: 'Тотем', players: { min: 3, max: null } },
    { name: 'Дуплет', players: { min: 3, max: null } },
    { name: 'Lord of the Rings: The Confrontation', players: { min: 2, max: 2 } },
    { name: 'Not Alone', players: { min: 4, max: 7 } },
    { name: 'Каменный век', players: { min: 2, max: 4 } },
    { name: 'Корова 006', players: { min: 4, max: 10 } },
    { name: 'Остров Скай', players: { min: 3, max: 5 } },
    { name: 'Libertalia', players: { min: 4, max: 6 } },
    { name: 'Кондотьер', players: { min: 3, max: 6 } },
    { name: 'Spyrium', players: { min: 3, max: 5 } },
    { name: 'Puzzle Strike', players: { min: 2, max: 4 } },
    { name: 'King of New York', players: { min: 3, max: 6 } },
    { name: 'Dixit', players: { min: 4, max: 12 } },
    { name: 'Криминалист: Убийство в Гонконге', players: { min: 5, max: 10 } },
    { name: 'Этнос', players: { min: 2, max: 6 } },
    { name: 'Наместник', players: { min: 2, max: 4 } },
    { name: 'Эвакуация', players: { min: 2, max: 5 } },
    { name: 'Hanabi & Ikebana', players: { min: 2, max: 5 } },
    { name: 'Mr. Jack in New York', players: { min: 2, max: 2 } },
    { name: 'No Thanks!', players: { min: 3, max: 5 } },
    { name: 'Dice Town', players: { min: 3, max: 5 } },
    { name: 'BANG! The Dice Game', players: { min: 5, max: 8 } },
    { name: 'Сопротивление', players: { min: 5, max: 10 } },
    { name: 'Gobbit', players: { min: 3, max: 8 } },
    { name: '7 Dragons', players: { min: 3, max: 5 } },
    { name: 'Блеф', players: { min: 3, max: 6 } },
    { name: 'Jenga', players: { min: 2, max: null } },
    { name: 'Братство Пара', players: { min: 3, max: 4 } },
    { name: 'One Night Ultimate Werewolf (Оборотень)', players: { min: 5, max: 10 } },
    { name: 'Carson City', players: { min: 4, max: 5 } },
    { name: 'Root', players: { min: 4, max: 4 } },
    { name: 'Лес: Легенда о Мантикоре', players: { min: 3, max: 4 } },
    { name: 'Манчкин (Звёздный)', players: { min: 4, max: 6 } },
    { name: 'Roll Through the Ages: The Bronze Age (eng)', players: { min: 2, max: 4 } },
    { name: 'Concept', players: { min: 3, max: null } },
    { name: 'Voluspa', players: { min: 2, max: 4 } },
    { name: 'Битва Легенд. Воскрешённые', players: { min: 4, max: 6 } },
    { name: 'Таинственный Лабиринт', players: { min: 2, max: 4 } },
    { name: 'TSCHAK!', players: { min: 3, max: 4 } },
    { name: 'Mr. Jack Pocket', players: { min: 2, max: 2 } },
    { name: 'Калах', players: { min: 2, max: 2 } },
    { name: 'Can\'t Stop', players: { min: 2, max: 4 } },
    { name: 'Garden Dice', players: { min: 2, max: 4 } },
    { name: 'Love Letter', players: { min: 3, max: 4 } },
    { name: 'Ghost Stories', players: { min: 3, max: 4 } },
    { name: 'Age of War (Касугаяма)', players: { min: 3, max: 5 } },
    { name: 'Hive', players: { min: 2, max: 2 } },

]